

# A generic, single database configuration.

[alembic]
# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false


# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic,flask_migrate

[handlers]
keys = console,root_file,sqlalchemy_file,alembic_file,flask_migrate_file

[formatters]
keys = root_fmt,sqlalchemy_fmt,alembic_fmt, flask_migrate_fmt

[logger_root]
level = WARN
handlers = console,root_file
qualname =

[logger_sqlalchemy]
level = WARN
handlers =sqlalchemy_file
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =alembic_file
qualname = alembic

[logger_flask_migrate]
level = INFO
handlers =flask_migrate_file
qualname = flask_migrate

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = root_fmt

[handler_root_file]
class = FileHandler
args = ('logs/root.log')
level = WARN
formatter = root_fmt

[handler_sqlalchemy_file] 
class = FileHandler 
args = ('logs/sqlalchemy.log', 'a') 
level = INFO 
formatter = sqlalchemy_fmt 

[handler_alembic_file] 
class = FileHandler 
args = ('logs/alembic.log', 'a') 
level = INFO 
formatter = alembic_fmt


[handler_flask_migrate_file] 
class = FileHandler 
args = ('logs/flask_migrate.log', 'a') 
level = INFO 
formatter = flask_migrate_fmt 

[formatter_root_fmt] 
format = [%(asctime)s] [%(levelname)s] [ROOT] %(message)s 
datefmt = %Y-%m-%d %H:%M:%S 

[formatter_sqlalchemy_fmt] 
format = [%(asctime)s] [%(levelname)s] [SQLAlchemy] %(name)s: %(message)s 
datefmt = %d-%b-%Y %H:%M:%S 

[formatter_alembic_fmt] 
format = [%(asctime)s] [%(levelname)s] [Alembic] %(message)s 
datefmt = %A, %d %B %Y %H:%M:%S 

[formatter_flask_migrate_fmt] 
format = [%(asctime)s] [%(levelname)s] [Flask-Migrate] %(message)s 
datefmt = %d/%m/%Y %I:%M:%S %p
